name: prezence_api
description: A web server built using the shelf package.
# version: 1.0.0
# homepage: https://www.example.com
# author: Kenneth Reilly <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  args: ^1.4.2
  shelf: ^0.7.2
  postgres: 1.0.2
  dotenv: 1.0.0

dev_dependencies:
  pedantic: ^1.0.0
  build_runner: 'any'
  build_web_compilers: 'any'